/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Form;

import Konfigurasi.Koneksi;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;

/**
 *
 * @author ACER
 */
public class main_form extends javax.swing.JFrame {
    
    private DefaultTableModel DftTblModel_sellers;
    private DefaultTableModel DftTblModel_products;
    private String SQL;

    /**
     * Creates new form main_form
     */
    public main_form() {
        initComponents();
        this.TampilDataSellers();
        this.product_TampilData();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    private void TampilDataSellers() {
        DftTblModel_sellers = new DefaultTableModel();
        DftTblModel_sellers.addColumn("KODE SELLER");
        DftTblModel_sellers.addColumn("NAMA SELLER");
        DftTblModel_sellers.addColumn("ALAMAT");
        DftTblModel_sellers.addColumn("KODE POS");
        DftTblModel_sellers.addColumn("EMAIL");
        DftTblModel_sellers.addColumn("NO TELP");
        jTable_sellers.setModel(DftTblModel_sellers);
        Connection conn = Koneksi.getConnection();
        try {
            java.sql.Statement stmt = conn.createStatement();
            SQL = "select * from sellers";
            java.sql.ResultSet res = stmt.executeQuery(SQL);
            while (res.next()) {
                DftTblModel_sellers.addRow(new Object[]{
                    res.getString("id"),
                    res.getString("seller_name"),
                    res.getString("address"),
                    res.getString("postal_code"),
                    res.getString("email"),
                    res.getString("phone")
                });
            }
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
    }
    private void product_TampilData() {
        DftTblModel_products = new DefaultTableModel();
        DftTblModel_products.addColumn("id");
        DftTblModel_products.addColumn("name");
        DftTblModel_products.addColumn("quantity");
        DftTblModel_products.addColumn("category");
        DftTblModel_products.addColumn("price");
        DftTblModel_products.addColumn("seller_id");

        jTable_products.setModel(DftTblModel_products);
        Connection conn = Koneksi.getConnection();
        try {
            java.sql.Statement stmt = conn.createStatement();
            SQL = "select * from products";
            java.sql.ResultSet res = stmt.executeQuery(SQL);
            while (res.next()) {
                DftTblModel_products.addRow(new Object[]{
                    res.getString("id"),
                    res.getString("name"),
                    res.getString("quantity"),
                    res.getString("category"),
                    res.getString("price"),
                    res.getString("seller_id")
                });
            }
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane_container = new javax.swing.JTabbedPane();
        jPanel_products = new javax.swing.JPanel();
        product_id = new javax.swing.JTextField();
        product_name = new javax.swing.JTextField();
        product_quantity = new javax.swing.JTextField();
        product_category = new javax.swing.JTextField();
        product_price = new javax.swing.JTextField();
        product_seller_id = new javax.swing.JTextField();
        product_simpan = new javax.swing.JButton();
        product_edit = new javax.swing.JButton();
        product_hapus = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable_products = new javax.swing.JTable();
        jPanel_sellers = new javax.swing.JPanel();
        jTextField_sellers_kode = new javax.swing.JTextField();
        jLabel_sellers_kode = new javax.swing.JLabel();
        jLabel_sellers_judul = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel_sellers_nama = new javax.swing.JLabel();
        jTextField_sellers_nama = new javax.swing.JTextField();
        jLabel_sellers_alamat = new javax.swing.JLabel();
        jTextField_sellers_alamat = new javax.swing.JTextField();
        jLabel_sellers_kodepos = new javax.swing.JLabel();
        jTextField_sellers_kodepos = new javax.swing.JTextField();
        jTextField_sellers_telepon = new javax.swing.JTextField();
        jTextField_sellers_email = new javax.swing.JTextField();
        jLabel_sellers_telepon = new javax.swing.JLabel();
        jLabel_sellers_email = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_sellers = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane_container.setPreferredSize(new java.awt.Dimension(738, 657));

        product_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                product_idActionPerformed(evt);
            }
        });

        product_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                product_nameActionPerformed(evt);
            }
        });

        product_seller_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                product_seller_idActionPerformed(evt);
            }
        });

        product_simpan.setText("simpan");
        product_simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                product_simpanActionPerformed(evt);
            }
        });

        product_edit.setText("edit");
        product_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                product_editActionPerformed(evt);
            }
        });

        product_hapus.setText("hapus");
        product_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                product_hapusActionPerformed(evt);
            }
        });

        jLabel1.setText("Id");

        jLabel2.setText("Name");

        jLabel3.setText("Quantity");

        jLabel4.setText("Category");

        jLabel5.setText("Price");

        jLabel7.setText("Seller id");

        jTable_products.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable_products.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_productsMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable_products);

        javax.swing.GroupLayout jPanel_productsLayout = new javax.swing.GroupLayout(jPanel_products);
        jPanel_products.setLayout(jPanel_productsLayout);
        jPanel_productsLayout.setHorizontalGroup(
            jPanel_productsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_productsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_productsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 752, Short.MAX_VALUE)
                    .addGroup(jPanel_productsLayout.createSequentialGroup()
                        .addGroup(jPanel_productsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel_productsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel_productsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel_productsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel_productsLayout.createSequentialGroup()
                                .addComponent(product_simpan)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(product_edit)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(product_hapus))
                            .addComponent(product_id)
                            .addComponent(product_name)
                            .addComponent(product_quantity)
                            .addComponent(product_category)
                            .addComponent(product_price)
                            .addComponent(product_seller_id))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel_productsLayout.setVerticalGroup(
            jPanel_productsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_productsLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel_productsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(product_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_productsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(product_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_productsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(product_quantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_productsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(product_category, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_productsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(product_price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_productsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(product_seller_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jPanel_productsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(product_simpan)
                    .addComponent(product_edit)
                    .addComponent(product_hapus))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane_container.addTab("Products", jPanel_products);

        jTextField_sellers_kode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_sellers_kodeActionPerformed(evt);
            }
        });

        jLabel_sellers_kode.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel_sellers_kode.setText("Kode ");

        jLabel_sellers_judul.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel_sellers_judul.setText("DAFTAR PENJUAL");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel_sellers_nama.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel_sellers_nama.setText("Nama");

        jTextField_sellers_nama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_sellers_namaActionPerformed(evt);
            }
        });

        jLabel_sellers_alamat.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel_sellers_alamat.setText("Alamat");

        jTextField_sellers_alamat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_sellers_alamatActionPerformed(evt);
            }
        });

        jLabel_sellers_kodepos.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel_sellers_kodepos.setText("Kode Pos");

        jTextField_sellers_kodepos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_sellers_kodeposActionPerformed(evt);
            }
        });

        jTextField_sellers_telepon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_sellers_teleponActionPerformed(evt);
            }
        });

        jTextField_sellers_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_sellers_emailActionPerformed(evt);
            }
        });

        jLabel_sellers_telepon.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel_sellers_telepon.setText("Nomor Telepon");

        jLabel_sellers_email.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel_sellers_email.setText("Email ");

        jTable_sellers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable_sellers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_sellersMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_sellers);

        jButton1.setText("Simpan");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Edit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Hapus");

        javax.swing.GroupLayout jPanel_sellersLayout = new javax.swing.GroupLayout(jPanel_sellers);
        jPanel_sellers.setLayout(jPanel_sellersLayout);
        jPanel_sellersLayout.setHorizontalGroup(
            jPanel_sellersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_sellersLayout.createSequentialGroup()
                .addGroup(jPanel_sellersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_sellersLayout.createSequentialGroup()
                        .addGap(293, 293, 293)
                        .addComponent(jLabel_sellers_judul))
                    .addGroup(jPanel_sellersLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel6))
                    .addGroup(jPanel_sellersLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jPanel_sellersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel_sellersLayout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton3))
                            .addComponent(jLabel_sellers_kode)
                            .addComponent(jTextField_sellers_kode, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_sellers_nama)
                            .addComponent(jTextField_sellers_nama, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_sellers_alamat)
                            .addComponent(jTextField_sellers_alamat, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_sellers_kodepos)
                            .addComponent(jTextField_sellers_kodepos, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_sellers_telepon, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_sellers_email, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_sellers_telepon)
                            .addComponent(jLabel_sellers_email))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(39, 39, 39))
        );
        jPanel_sellersLayout.setVerticalGroup(
            jPanel_sellersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_sellersLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_sellers_judul)
                .addGap(14, 14, 14)
                .addGroup(jPanel_sellersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_sellersLayout.createSequentialGroup()
                        .addComponent(jLabel_sellers_kode)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_sellers_kode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(jLabel_sellers_nama)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_sellers_nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(jLabel_sellers_alamat)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_sellers_alamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(jLabel_sellers_kodepos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_sellers_kodepos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(jLabel_sellers_email)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_sellers_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(jLabel_sellers_telepon)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_sellers_telepon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel_sellersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton3)
                            .addComponent(jButton1)
                            .addComponent(jButton2)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(144, 144, 144)
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane_container.addTab("Sellers", jPanel_sellers);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 753, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 593, Short.MAX_VALUE)
        );

        jTabbedPane_container.addTab("Customers", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane_container, javax.swing.GroupLayout.PREFERRED_SIZE, 758, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane_container, javax.swing.GroupLayout.PREFERRED_SIZE, 621, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_sellers_kodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_sellers_kodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_sellers_kodeActionPerformed

    private void jTextField_sellers_namaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_sellers_namaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_sellers_namaActionPerformed

    private void jTextField_sellers_alamatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_sellers_alamatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_sellers_alamatActionPerformed

    private void jTextField_sellers_kodeposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_sellers_kodeposActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_sellers_kodeposActionPerformed

    private void jTextField_sellers_teleponActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_sellers_teleponActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_sellers_teleponActionPerformed

    private void jTextField_sellers_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_sellers_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_sellers_emailActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try {
            Connection conn = Koneksi.getConnection();
            PreparedStatement stmt = conn.prepareStatement("insert into sellers(id, seller_name, address, postal_code, email, phone) values(?,?,?,?,?,?)");
            stmt.setString(1, jTextField_sellers_kode.getText());
            stmt.setString(2, jTextField_sellers_nama.getText());
            stmt.setString(3, jTextField_sellers_alamat.getText());
            stmt.setString(4, jTextField_sellers_kodepos.getText());
            stmt.setString(5, jTextField_sellers_email.getText());
            stmt.setString(6, jTextField_sellers_telepon.getText());
            stmt.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data berhasil disimpan", "Pesan", JOptionPane.INFORMATION_MESSAGE);
            TampilDataSellers();
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTable_sellersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_sellersMouseClicked
        int baris = jTable_sellers.getSelectedRow();
        jTextField_sellers_kode.setText(DftTblModel_sellers.getValueAt(baris, 0).toString());
        jTextField_sellers_nama.setText(DftTblModel_sellers.getValueAt(baris, 1).toString());
        jTextField_sellers_alamat.setText(DftTblModel_sellers.getValueAt(baris, 2).toString());
        jTextField_sellers_kodepos.setText(DftTblModel_sellers.getValueAt(baris, 3).toString());
        jTextField_sellers_email.setText(DftTblModel_sellers.getValueAt(baris, 4).toString());
        jTextField_sellers_telepon.setText(DftTblModel_sellers.getValueAt(baris, 5).toString());
    }//GEN-LAST:event_jTable_sellersMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            Connection conn = Koneksi.getConnection();
            PreparedStatement stmt = conn.prepareStatement(
                    "update sellers"
                            + " set seller_name=?, address=?, postal_code=?,"
                            + " email=?, phone=? "
                            + "where id=?");
            stmt.setString(1, jTextField_sellers_nama.getText());
            stmt.setString(2, jTextField_sellers_alamat.getText());
            stmt.setString(3, jTextField_sellers_kodepos.getText());
            stmt.setString(4, jTextField_sellers_email.getText());
            stmt.setString(5, jTextField_sellers_telepon.getText());
            stmt.setString(6, jTextField_sellers_kode.getText());
            
            stmt.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data berhasil diubah", "Pesan", JOptionPane.INFORMATION_MESSAGE);
            TampilDataSellers();
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void product_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_product_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_product_idActionPerformed

    private void product_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_product_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_product_nameActionPerformed

    private void product_seller_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_product_seller_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_product_seller_idActionPerformed

    private void product_simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_product_simpanActionPerformed
        // TODO add your handling code here:
        try {
            Connection conn = Koneksi.getConnection();
            PreparedStatement stmt = conn.prepareStatement("insert into products(id, name, quantity, category, price, seller_id) values(?,?,?,?,?,?)");
            stmt.setString(1, product_id.getText());
            stmt.setString(2, product_name.getText());
            stmt.setString(3, product_quantity.getText());
            stmt.setString(4, product_category.getText());
            stmt.setString(5, product_price.getText());
            stmt.setString(6, product_seller_id.getText());
            stmt.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data berhasil disimpan", "Pesan", JOptionPane.INFORMATION_MESSAGE);
            product_TampilData();
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_product_simpanActionPerformed

    private void product_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_product_editActionPerformed
        // TODO add your handling code here:
        try {
            Connection conn = Koneksi.getConnection();
            PreparedStatement stmt = conn.prepareStatement("update products set name=?, quantity=?, category=?, price=?, seller_id=? where id=?");
            stmt.setString(1, product_name.getText());
            stmt.setString(2, product_quantity.getText());
            stmt.setString(3, product_category.getText());
            stmt.setString(4, product_price.getText());
            stmt.setString(5, product_seller_id.getText());
            stmt.setString(6, product_id.getText());

            stmt.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data berhasil diubah", "Pesan", JOptionPane.INFORMATION_MESSAGE);
            product_TampilData();
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_product_editActionPerformed

    private void product_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_product_hapusActionPerformed
        // TODO add your handling code here:
        Connection conn = Koneksi.getConnection();
        int confirm = JOptionPane.showConfirmDialog(null, "Apakah anda yakin ingin menghapus data tersebut?", "Konfirmasi", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (confirm == 0) {
            try {
                java.sql.PreparedStatement stmt = conn.prepareStatement("delete from products where id ='" + product_id.getText() + "'");
                stmt.executeUpdate();
                JOptionPane.showMessageDialog(null, "Data berhasil dihapus", "Pesan", JOptionPane.INFORMATION_MESSAGE);
                product_TampilData();
                product_id.setText("");
                product_name.setText("");
                product_quantity.setText("");
                product_category.setText("");
                product_price.setText("");
                product_seller_id.setText("");
                product_id.requestFocus();
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "Data gagal di hapus" + e.getMessage(), "Pesan", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_product_hapusActionPerformed

    private void jTable_productsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_productsMouseClicked
        // TODO add your handling code here:
        int baris = jTable_products.getSelectedRow();
        product_id.setText(DftTblModel_products.getValueAt(baris, 0).toString());
        product_name.setText(DftTblModel_products.getValueAt(baris, 1).toString());
        product_quantity.setText(DftTblModel_products.getValueAt(baris, 2).toString());
        product_category.setText(DftTblModel_products.getValueAt(baris, 3).toString());
        product_price.setText(DftTblModel_products.getValueAt(baris, 4).toString());
        product_seller_id.setText(DftTblModel_products.getValueAt(baris, 5).toString());
    }//GEN-LAST:event_jTable_productsMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main_form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel_sellers_alamat;
    private javax.swing.JLabel jLabel_sellers_email;
    private javax.swing.JLabel jLabel_sellers_judul;
    private javax.swing.JLabel jLabel_sellers_kode;
    private javax.swing.JLabel jLabel_sellers_kodepos;
    private javax.swing.JLabel jLabel_sellers_nama;
    private javax.swing.JLabel jLabel_sellers_telepon;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel_products;
    private javax.swing.JPanel jPanel_sellers;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane_container;
    private javax.swing.JTable jTable_products;
    private javax.swing.JTable jTable_sellers;
    private javax.swing.JTextField jTextField_sellers_alamat;
    private javax.swing.JTextField jTextField_sellers_email;
    private javax.swing.JTextField jTextField_sellers_kode;
    private javax.swing.JTextField jTextField_sellers_kodepos;
    private javax.swing.JTextField jTextField_sellers_nama;
    private javax.swing.JTextField jTextField_sellers_telepon;
    private javax.swing.JTextField product_category;
    private javax.swing.JButton product_edit;
    private javax.swing.JButton product_hapus;
    private javax.swing.JTextField product_id;
    private javax.swing.JTextField product_name;
    private javax.swing.JTextField product_price;
    private javax.swing.JTextField product_quantity;
    private javax.swing.JTextField product_seller_id;
    private javax.swing.JButton product_simpan;
    // End of variables declaration//GEN-END:variables
}
